configurar deploy worker

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -152,8 +152,79 @@ jobs:
         env:
           IMAGE_URI: ${{ steps.build-image.outputs.image }}
         run: |
-          yq e '.spec.template.spec.containers[0].image = "'"$IMAGE_URI"'"' -i infra/k8s/01-api-deployment.yaml || { echo "Error updating ecr_image_url_repo_tag value"; exit 1; }
+          yq e '.spec.template.spec.containers[0].image = "'"$IMAGE_URI"'"' -i infra/k8s/api/01-api-deployment.yaml || { echo "Error updating ecr_image_url_repo_tag value"; exit 1; }
       
       - name: Deploy to EKS
         run: |
-          kubectl apply -f infra/k8s
+          kubectl apply -f infra/k8s/api
+
+
+  deploy-worker-status:
+    name: Worker Status Deploy
+    runs-on: ubuntu-latest
+    needs: build
+    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+    
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v3
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-session-token: ${{ secrets.AWS_SECRET_ACCESS_TOKEN }}
+          aws-region: ${{ vars.AWS_REGION }}
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+      
+      - name: Set up Docker
+        uses: docker/setup-buildx-action@v2
+      
+      - name: Build, tag, and push image to Amazon ECR
+        id: build-image
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: ${{ vars.VIDEOS_WORKER_STATUS_ECR_NAME }}
+          IMAGE_TAG: ${{ github.sha }}
+        run: |
+          docker build -f src/Driving/Vidsnap.Worker.AtualizaStatus/Vidsnap.Worker.AtualizaStatusProcessamento/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG src
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+        
+      - name: Install Kubectl
+        run: |
+          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+          chmod +x kubectl
+          sudo mv kubectl /usr/local/bin/
+
+      - name: Configure Kubectl
+        run: |
+          aws eks --region ${{ vars.AWS_REGION }} update-kubeconfig --name ${{ vars.PROJECT_NAME }}
+      
+      - name: Create/Update ConfigMap API Videos
+        env:
+          BUCKET: ${{ vars.VIDEOS_BUCKET_NAME }}
+          TIMEOUT_DEFAULT: 1 
+        run: |
+          CONFIGMAP_NAME="api-videos-configmap"
+      
+          if kubectl get configmap "$CONFIGMAP_NAME"  > /dev/null 2>&1; then
+            kubectl delete configmap "$CONFIGMAP_NAME" 
+          fi
+      
+          kubectl create configmap "$CONFIGMAP_NAME" \
+            --from-literal=bucket-name="${{ env.BUCKET }}" \
+            --from-literal=timeout-default="${{ env.TIMEOUT_DEFAULT }}"
+            
+      - name: Replace ECR image string value
+        env:
+          IMAGE_URI: ${{ steps.build-image.outputs.image }}
+        run: |
+          yq e '.spec.template.spec.containers[0].image = "'"$IMAGE_URI"'"' -i infra/k8s/worker/01-worker-deployment.yaml || { echo "Error updating ecr_image_url_repo_tag value"; exit 1; }
+      
+      - name: Deploy to EKS
+        run: |
+          kubectl apply -f infra/k8s/worker
